Ubuntu and shell script

diff --git a/.github/workflows/verify-code-style.yml b/.github/workflows/verify-code-style.yml
--- a/.github/workflows/verify-code-style.yml
+++ b/.github/workflows/verify-code-style.yml
@@ -31,7 +31,7 @@ on:
 jobs:
   verify-code-style:
     name: "Verify code style"
-    runs-on: windows-2019
+    runs-on: ubuntu-latest
     
     steps:
       - uses: actions/checkout@v4
@@ -47,7 +47,23 @@ jobs:
         run: dotnet build --nologo --verbosity normal Yubico.NET.SDK.sln
 
       - name: "Add DOTNET to path explicitly to address bug where it cannot be found"
-        run: echo "$(dirname $(readlink $(which dotnet)))" >> GITHUB_PATH
+        run: |
+          DOTNET_PATH=$(which dotnet)
+          if [ -z "$DOTNET_PATH" ]; then
+          echo "dotnet not found via which, checking /usr/share/dotnet"
+          # Finding all executables named dotnet and picking the first one
+          DOTNET_PATH=$(find /usr/share/dotnet -type f -name "dotnet" -executable | head -n 1)
+          fi
+          
+          if [ -z "$DOTNET_PATH" ]; then
+          echo "dotnet executable not found."
+          exit 1
+          else
+          echo "Using dotnet at $DOTNET_PATH"
+          DOTNET_DIR=$(dirname $(readlink -f $DOTNET_PATH))
+          echo "$DOTNET_DIR" >> $GITHUB_PATH
+          echo "Added $DOTNET_DIR to GITHUB_PATH"
+          fi
 
       - name: Check for correct formatting
         run: dotnet format --verify-no-changes --no-restore -v d
